name: example
description: An example usage of primer_progress_bar.
publish_to: "none"

version: 0.2.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  device_frame: ^1.1.0
  flutter:
    sdk: flutter
  primer_progress_bar:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
