name: primer_progress_bar
description: Unofficial Flutter implementation of the progress bar defined in GitHub Primer Design System.
version: 0.5.0
repository: https://github.com/fujidaiti/primer_progress_bar

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.6
